# Generated by Django 4.2.7 on 2024-08-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='volume',
            field=models.FloatField(verbose_name='Объем двигателя л'),
        ),
    ]
